apiVersion: v1
name: robot-shop-cd
version: 1.1.0
home: https://github.com/instana/robot-shop
description: Stan's Robot Shop — backend cluster (catalogue, user, ratings, dispatch, mongo, mysql, shipping)
