apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  annotations:
    env: {{ .Values.policyAnnotations.env | quote }}
    owner: {{ .Values.policyAnnotations.owner | quote }}
  labels:
    service: mysql
  name: mysql
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    service: mysql
