apiVersion: v1
kind: ResourceQuota
metadata:
  name: robot-shop-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "25"
    services: "15"
    persistentvolumeclaims: "5"
