apiVersion: v1
kind: LimitRange
metadata:
  name: robot-shop-default-limits
  namespace: {{ .Values.namespace }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.resourceDefaults.limits.cpu | quote }}
        memory: {{ .Values.resourceDefaults.limits.memory | quote }}
      defaultRequest:
        cpu: {{ .Values.resourceDefaults.requests.cpu | quote }}
        memory: {{ .Values.resourceDefaults.requests.memory | quote }}
