apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-wallarm-to-web
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      service: web
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: wallarm-ingress
      ports:
        - protocol: TCP
          port: 8080
