apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  annotations:
    env: {{ .Values.policyAnnotations.env | quote }}
    owner: {{ .Values.policyAnnotations.owner | quote }}
  name: ratings
  labels:
    service: ratings
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: ratings

